import type { ShopItem, NightMarketSlot } from './types'

// Real backgrounds from Supabase public_backgrounds
const REAL_BG_BAMBOO = "https://res.cloudinary.com/pachi/image/upload/v1779608163/default_bg2_ffgpqn.png"
const REAL_BG_WASHITSU = "https://res.cloudinary.com/pachi/image/upload/v1779608445/default_bg_x1by5d.jpg"

// Stable placeholder backgrounds via Picsum (seed-based, never changes)
const P = (seed: number, w = 800, h = 450) => `https://picsum.photos/seed/${seed}/${w}/${h}`

export const MOCK_SHOP_ITEMS: ShopItem[] = [
  // ── BUNDLES (always top, biggest) ────────────────────────────────────────

  {
    id: "bundle-sakura-festival",
    name: "Sakura Festival Bundle",
    description: "A full spring collection — 6 scenic backgrounds, 2 dialogue skins, and a rare profile frame. Limited to the cherry blossom season.",
    item_type: "bundle",
    price_coins: null,
    price_gems: 280,
    available_from: null,
    available_until: null,
    is_active: true,
    is_night_market_eligible: false,
    rarity: "legendary",
    metadata: {
      preview_url: P(10, 1200, 600),
      contains: [
        { item_type: "background_pack", name: "Cherry Blossom Path", preview: P(10) },
        { item_type: "background_pack", name: "Sakura Shrine Gate", preview: P(11) },
        { item_type: "background_pack", name: "Petal Waterfall Cliff", preview: P(12) },
        { item_type: "background_pack", name: "Night Blossom Temple", preview: P(13) },
        { item_type: "background_pack", name: "Spring Market Street", preview: P(14) },
        { item_type: "background_pack", name: "Rooftop Petal Rain", preview: P(15) },
        { item_type: "dialogue_skin", name: "Petal Whisper UI", preview: P(16, 400, 200) },
        { item_type: "dialogue_skin", name: "Ink & Bloom UI", preview: P(17, 400, 200) },
      ],
      tag: "FESTIVAL",
      badge_color: "#f472b6",
    },
  },

  {
    id: "bundle-midnight-noir",
    name: "Midnight Noir Bundle",
    description: "Dark urban aesthetics — 5 noir cityscape backgrounds and a sleek black dialogue skin with neon accents.",
    item_type: "bundle",
    price_coins: null,
    price_gems: 220,
    available_from: null,
    available_until: null,
    is_active: true,
    is_night_market_eligible: false,
    rarity: "epic",
    metadata: {
      preview_url: P(20, 1200, 600),
      contains: [
        { item_type: "background_pack", name: "Rain-slicked Alley", preview: P(20) },
        { item_type: "background_pack", name: "Neon Rooftop Bar", preview: P(21) },
        { item_type: "background_pack", name: "Subway at 3 AM", preview: P(22) },
        { item_type: "background_pack", name: "Detective's Office", preview: P(23) },
        { item_type: "background_pack", name: "Penthouse Overlook", preview: P(24) },
        { item_type: "dialogue_skin", name: "Neon Noir UI", preview: P(25, 400, 200) },
      ],
      tag: "NOIR",
      badge_color: "#6d28d9",
    },
  },

  {
    id: "bundle-cozy-winter",
    name: "Cozy Winter Bundle",
    description: "Warm indoors and snowy outdoors — 4 winter backgrounds, a fireplace dialogue skin, and a snowfall particle effect.",
    item_type: "bundle",
    price_coins: 2800,
    price_gems: null,
    available_from: null,
    available_until: null,
    is_active: true,
    is_night_market_eligible: true,
    rarity: "rare",
    metadata: {
      preview_url: P(30, 1200, 600),
      contains: [
        { item_type: "background_pack", name: "Frosted Library", preview: REAL_BG_WASHITSU },
        { item_type: "background_pack", name: "Snowy Bamboo Grove", preview: REAL_BG_BAMBOO },
        { item_type: "background_pack", name: "Warm Café Window", preview: P(31) },
        { item_type: "background_pack", name: "Cabin by the Lake", preview: P(32) },
        { item_type: "dialogue_skin", name: "Hearth & Snow UI", preview: P(33, 400, 200) },
      ],
      tag: "WINTER",
      badge_color: "#0ea5e9",
    },
  },

  {
    id: "bundle-campus-chronicles",
    name: "Campus Chronicles Bundle",
    description: "School life essentials — 5 academy backgrounds perfect for slice-of-life and romance stories.",
    item_type: "bundle",
    price_coins: 1800,
    price_gems: null,
    available_from: null,
    available_until: null,
    is_active: true,
    is_night_market_eligible: true,
    rarity: "common",
    metadata: {
      preview_url: P(40, 1200, 600),
      contains: [
        { item_type: "background_pack", name: "Rooftop at Lunch", preview: P(40) },
        { item_type: "background_pack", name: "Empty Classroom Dusk", preview: P(41) },
        { item_type: "background_pack", name: "School Gate Morning", preview: P(42) },
        { item_type: "background_pack", name: "Library Stacks", preview: P(43) },
        { item_type: "background_pack", name: "Gymnasium Night", preview: P(44) },
      ],
      tag: "SCHOOL",
      badge_color: "#f59e0b",
    },
  },

  {
    id: "bundle-supernatural",
    name: "Supernatural Realm Bundle",
    description: "Spirit worlds, haunted shrines, and otherworldly vistas — 6 supernatural backgrounds + a ghostly dialogue skin.",
    item_type: "bundle",
    price_coins: null,
    price_gems: 260,
    available_from: null,
    available_until: null,
    is_active: true,
    is_night_market_eligible: false,
    rarity: "epic",
    metadata: {
      preview_url: P(50, 1200, 600),
      contains: [
        { item_type: "background_pack", name: "Floating Torii Gate", preview: P(50) },
        { item_type: "background_pack", name: "Spirit Market", preview: P(51) },
        { item_type: "background_pack", name: "Moonlit Yokai Forest", preview: P(52) },
        { item_type: "background_pack", name: "Abandoned Shrine Rain", preview: P(53) },
        { item_type: "background_pack", name: "Underworld River", preview: P(54) },
        { item_type: "background_pack", name: "Celestial Palace", preview: P(55) },
        { item_type: "dialogue_skin", name: "Spirit Veil UI", preview: P(56, 400, 200) },
      ],
      tag: "SUPERNATURAL",
      badge_color: "#8b5cf6",
    },
  },

  // ── INDIVIDUAL BACKGROUND PACKS ───────────────────────────────────────────

  {
    id: "bg-bamboo-courtyard",
    name: "Bamboo Courtyard",
    description: "A tranquil bamboo courtyard at golden hour — the classic Jikkei starter background.",
    item_type: "background_pack",
    price_coins: 300,
    price_gems: null,
    available_from: null,
    available_until: null,
    is_active: true,
    is_night_market_eligible: true,
    rarity: "common",
    metadata: {
      backgrounds: [REAL_BG_BAMBOO],
      preview_url: REAL_BG_BAMBOO,
    },
  },

  {
    id: "bg-washitsu-bedroom",
    name: "Washitsu Bedroom",
    description: "A traditional Japanese tatami room with soft afternoon light. Intimate and warm.",
    item_type: "background_pack",
    price_coins: 300,
    price_gems: null,
    available_from: null,
    available_until: null,
    is_active: true,
    is_night_market_eligible: true,
    rarity: "common",
    metadata: {
      backgrounds: [REAL_BG_WASHITSU],
      preview_url: REAL_BG_WASHITSU,
    },
  },

  {
    id: "bg-rainy-café",
    name: "Rainy Day Café",
    description: "A cozy corner table as rain streaks down the window. Perfect for slow-burn romance.",
    item_type: "background_pack",
    price_coins: 450,
    price_gems: null,
    available_from: null,
    available_until: null,
    is_active: true,
    is_night_market_eligible: true,
    rarity: "common",
    metadata: { backgrounds: [P(60)], preview_url: P(60) },
  },

  {
    id: "bg-moonlit-park",
    name: "Moonlit Park",
    description: "A park bench under a full moon — the perfect confession scene backdrop.",
    item_type: "background_pack",
    price_coins: 450,
    price_gems: null,
    available_from: null,
    available_until: null,
    is_active: true,
    is_night_market_eligible: true,
    rarity: "common",
    metadata: { backgrounds: [P(61)], preview_url: P(61) },
  },

  {
    id: "bg-seaside-cliff",
    name: "Seaside Cliff",
    description: "A dramatic cliff overlooking the ocean at dusk. High drama, higher stakes.",
    item_type: "background_pack",
    price_coins: 500,
    price_gems: null,
    available_from: null,
    available_until: null,
    is_active: true,
    is_night_market_eligible: true,
    rarity: "rare",
    metadata: { backgrounds: [P(62)], preview_url: P(62) },
  },

  {
    id: "bg-train-window",
    name: "Train at Sunset",
    description: "Looking out a train window as countryside rolls by at golden hour. Wistful and cinematic.",
    item_type: "background_pack",
    price_coins: 500,
    price_gems: null,
    available_from: null,
    available_until: null,
    is_active: true,
    is_night_market_eligible: true,
    rarity: "rare",
    metadata: { backgrounds: [P(63)], preview_url: P(63) },
  },

  {
    id: "bg-festival-fireworks",
    name: "Summer Festival Night",
    description: "A matsuri street lit up with lanterns, fireworks bursting overhead.",
    item_type: "background_pack",
    price_coins: 600,
    price_gems: null,
    available_from: null,
    available_until: null,
    is_active: true,
    is_night_market_eligible: true,
    rarity: "rare",
    metadata: { backgrounds: [P(64)], preview_url: P(64) },
  },

  {
    id: "bg-haunted-mansion",
    name: "Haunted Mansion Foyer",
    description: "Cobwebs, candlelight, and creaking floorboards. For horror and mystery arcs.",
    item_type: "background_pack",
    price_coins: 650,
    price_gems: null,
    available_from: null,
    available_until: null,
    is_active: true,
    is_night_market_eligible: true,
    rarity: "rare",
    metadata: { backgrounds: [P(65)], preview_url: P(65) },
  },

  {
    id: "bg-northern-lights",
    name: "Northern Lights Tundra",
    description: "An aurora-lit snowfield at midnight. Ethereal and breathtaking.",
    item_type: "background_pack",
    price_coins: null,
    price_gems: 60,
    available_from: null,
    available_until: null,
    is_active: true,
    is_night_market_eligible: true,
    rarity: "epic",
    metadata: { backgrounds: [P(66)], preview_url: P(66) },
  },

  {
    id: "bg-floating-island",
    name: "Floating Sky Island",
    description: "A lush island suspended in the clouds above a sea of mist.",
    item_type: "background_pack",
    price_coins: null,
    price_gems: 80,
    available_from: null,
    available_until: null,
    is_active: true,
    is_night_market_eligible: false,
    rarity: "epic",
    metadata: { backgrounds: [P(67)], preview_url: P(67) },
  },

  {
    id: "bg-ancient-library",
    name: "Ancient Infinite Library",
    description: "Bookshelves stretching into infinity, warm amber light, and the smell of old paper.",
    item_type: "background_pack",
    price_coins: null,
    price_gems: 90,
    available_from: null,
    available_until: null,
    is_active: true,
    is_night_market_eligible: false,
    rarity: "legendary",
    metadata: { backgrounds: [P(68)], preview_url: P(68) },
  },

  // ── INDIVIDUAL DIALOGUE SKINS ─────────────────────────────────────────────

  {
    id: "skin-sakura-pink",
    name: "Sakura Pink UI",
    description: "A soft pink petal theme with cherry blossom decorations. The default Jikkei aesthetic, elevated.",
    item_type: "dialogue_skin",
    price_coins: 800,
    price_gems: null,
    available_from: null,
    available_until: null,
    is_active: true,
    is_night_market_eligible: true,
    rarity: "common",
    metadata: {
      theme_key: "sakura_pink",
      preview_url: P(70, 600, 300),
      coming_soon: false,
    },
  },

  {
    id: "skin-midnight-glass",
    name: "Midnight Glass UI",
    description: "Dark frosted glass with subtle neon pink accents. Sleek, modern, cinematic.",
    item_type: "dialogue_skin",
    price_coins: null,
    price_gems: 45,
    available_from: null,
    available_until: null,
    is_active: true,
    is_night_market_eligible: true,
    rarity: "rare",
    metadata: {
      theme_key: "midnight_glass",
      preview_url: P(71, 600, 300),
      coming_soon: false,
    },
  },

  {
    id: "skin-golden-scroll",
    name: "Golden Scroll UI",
    description: "Gilded parchment texture with ornate calligraphy borders. For epic fantasy tales.",
    item_type: "dialogue_skin",
    price_coins: null,
    price_gems: 70,
    available_from: null,
    available_until: null,
    is_active: true,
    is_night_market_eligible: true,
    rarity: "epic",
    metadata: {
      theme_key: "golden_scroll",
      preview_url: P(72, 600, 300),
      coming_soon: false,
    },
  },

  {
    id: "skin-aurora-dream",
    name: "Aurora Dream UI",
    description: "Shifting northern lights gradients behind translucent glass panels. Legendary rarity.",
    item_type: "dialogue_skin",
    price_coins: null,
    price_gems: 150,
    available_from: null,
    available_until: null,
    is_active: true,
    is_night_market_eligible: false,
    rarity: "legendary",
    metadata: {
      theme_key: "aurora_dream",
      preview_url: P(73, 600, 300),
      coming_soon: false,
    },
  },

  {
    id: "skin-retro-terminal",
    name: "Retro Terminal UI",
    description: "Green-on-black CRT phosphor aesthetic. For cyberpunk and sci-fi stories.",
    item_type: "dialogue_skin",
    price_coins: 1200,
    price_gems: null,
    available_from: null,
    available_until: null,
    is_active: true,
    is_night_market_eligible: true,
    rarity: "rare",
    metadata: {
      theme_key: "retro_terminal",
      preview_url: P(74, 600, 300),
      coming_soon: false,
    },
  },
]

// Night market mock — 5 slots, mix of revealed/unrevealed
export const MOCK_NIGHT_MARKET: {
  week_start: string
  next_reset: string
  slots: NightMarketSlot[]
} = {
  week_start: "2026-06-29T17:00:00Z",
  next_reset: "2026-07-06T17:00:00Z",
  slots: [
    {
      slot_index: 0,
      shop_item_id: "bg-rainy-café",
      discount_pct: 40,
      is_night_market_only: false,
      is_revealed: false,
      is_purchased: false,
      item: MOCK_SHOP_ITEMS.find(i => i.id === "bg-rainy-café") ?? null,
    },
    {
      slot_index: 1,
      shop_item_id: "skin-midnight-glass",
      discount_pct: 35,
      is_night_market_only: false,
      is_revealed: false,
      is_purchased: false,
      item: MOCK_SHOP_ITEMS.find(i => i.id === "skin-midnight-glass") ?? null,
    },
    {
      slot_index: 2,
      shop_item_id: "bg-festival-fireworks",
      discount_pct: 50,
      is_night_market_only: true,
      is_revealed: false,
      is_purchased: false,
      item: MOCK_SHOP_ITEMS.find(i => i.id === "bg-festival-fireworks") ?? null,
    },
    {
      slot_index: 3,
      shop_item_id: "bg-northern-lights",
      discount_pct: 30,
      is_night_market_only: false,
      is_revealed: false,
      is_purchased: false,
      item: MOCK_SHOP_ITEMS.find(i => i.id === "bg-northern-lights") ?? null,
    },
    {
      slot_index: 4,
      shop_item_id: "skin-golden-scroll",
      discount_pct: 45,
      is_night_market_only: false,
      is_revealed: false,
      is_purchased: false,
      item: MOCK_SHOP_ITEMS.find(i => i.id === "skin-golden-scroll") ?? null,
    },
  ],
}
